### ISSUE TITLE
Color of link in footer

### ISSUE THREAD

**Issue by JakobMiksch** [meggsimum/wegue#172]
PR #165 changed the style of the link in the footer. 
However, this does not seem to work for once the app has been build.
Then color of the link is blue again.

**Comment by JakobMiksch** [comment]
in ` app/components/AppFooter.vue` this adding `!important` should fix it:
```css
.v-application a {
    color: inherit !important;
  }
```
